### ISSUE TITLE
Develop manual and automated index refresh triggers

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/web-redesign#199]
This option will be a short-term solution until emory-libraries/templating-engine#30 is resolved. We can add a button to every page in cascade that triggers an index. This will mostly be needed for the `staging` environment in order for content editors to be able to preview their changes. We will also set up a cron job to run on production as a failsafe in case content editors forget to update the index on the production site.

# API Trigger
The trigger will do the following:
- [x] Use JS to make the API call.
- [x] Setup a PHP proxy to relay the JS API call to the right indexer script
- [x] Update the index on all servers.
- [x] Build a queue in case multiple index requests are submitted sequentially.

# Cron Job
The cron job will do the following:
- [x] Run hourly
- [x] Auto initiate if the server reboots.

**Comment by laurenhamel** [comment]
Cascade triggers are in place, and the cron jobs have been setup.

**Comment by kristianserrano** [comment]
@nikdragovic This is ready for content folks to test in Cascade.

**Comment by nikdragovic** [comment]
@kristianserrano Will close this when I get confirmation from content folks.

**Comment by nikdragovic** [comment]
@kristianserrano I confirmed acceptance with Kim Collins; the steps to use this feature have also been documented and shared. She had another question she was expecting Doug to follow up on: what is the time to index if manual indexing is not used?
