### ISSUE TITLE
Consider using a cover page for news and publications

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#259]
Once the publications section launches (see epic #345), an index page will be used to lead users to the blog and publications.  Ideally we would have a more robust news section the way Viget envisioned it.  Consider using implementing a [cover page template](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-cover) for the News and Publications.

- [ ] identify a calendar for featured news stories
- [ ] identify how to feature publications
- [ ] identify related content to highlight
- [ ] identify feeds to feature at the bottom of the page

**Comment by cwbragg** [comment]
These pages have been created and are now live. 

https://libraries.emory.edu/events-exhibits/index.html

https://libraries.emory.edu/news/index.html

The cover page template only allows for two calendars to display at the bottom. If we could remove this, I could add one relevant calendar for each page.
