### ISSUE TITLE
Prepare site for launch of publications section

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#260]
We are launching the new Emory Libraries website without the publications section.  This Epic provides a high level overview of everything that needs to be accomplished in order to launch the publications section

- [ ] remove existing redirects to publications
- [ ] implement new redirects for publications
- [ ] QA the template provided by Hannon Hill
- [ ] review content for images
- [ ] review content for broken links
- [ ] review content for spelling and grammar
- [ ] create a news index page; this should link to the different content sources like publications and the blog
- [ ] update links in the utility navigation and the footer to take into account this section
