### ISSUE TITLE
Redesign the Support Emory Libraries Section

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#265]
Erin got back to me about the support emory libraries section of the website.  She has the following requests:

- [ ] Create an index page at /about/support-emory-libraries/index.html; note that a shell of this page exists at index-new.html right now. The page should link to the following pages: 
  - [ ] Twelfth Night Revel: page exists at - /about/support-emory-libraries/twelfth-night-2019.html
  - [ ] Honor with Books: page does not exist, content does not exist
  - [ ] Friends of Emory Libraries: page does not exist, content does not exist
  - [ ] Donors Support Innovation: page does not exist
  - [ ] Donor Spotlight: page does not exist
- [ ] Endowment supports undergraduate research awards
